name: ci

on:
  push:
    branches:    
      - main 
  pull_request:
    branches:    
      - main   

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing
      run: yarn install --frozen-lockfile
    - name: Linting
      run: yarn lint
    - name: Building
      run: yarn build
    - name: Testing
      run: yarn test
    - name: Anti-tamper check
      run: git diff --exit-code
